CREATE TABLE BOOK (
    ID VARCHAR(255) PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    PUBLICATION_YEAR DATE,
    ISBN VARCHAR(20),
    IS_BORROWED VARCHAR(1)
);

CREATE TABLE PATRON (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    MOBILE VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    BIRTHDATE DATE,
    BORROWED_BOOK_IDS VARCHAR(225)
);
 
CREATE TABLE BORROWING_RECORD (
    ID VARCHAR(255) PRIMARY KEY,
    BOOK_ID VARCHAR(255) NOT NULL,
    PATRON_ID VARCHAR(255) NOT NULL,
    BORROW_DATE DATE,
    RETURN_DATE DATE,
    FOREIGN KEY (BOOK_ID) REFERENCES Book(ID),
    FOREIGN KEY (PATRON_ID) REFERENCES Patron(ID)
    
);

